version: '3'

services:
  trustmnw:
    container_name: trustmnw
    restart: unless-stopped
    build: .
    tty: true
    networks:
      - web
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data/home:/home
      - ./data/tmp:/tmp/node/trustmnw-cli
# uncomment to have healthcheck, notice you need to login within start_period, otherwise will cause restarts
#    healthcheck:
#      test: grep -c '\"connected\":true' /tmp/node/trustmnw-cli/trustmnw-stats.json
#      start_period: 60s
#      interval: 30s
#      timeout: 3s
#      retries: 5
    command: bash -c "/usr/local/bin/trustmnw-cli restart && bash"

networks:
  web:
    external: true
